games/urls.py
from django.urls import path

from games.views import AboutUsView, HomePageView, MathFactsView, AnagramHuntView

app_name = 'games'
urlpatterns = [
    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('', HomePageView.as_view(), name='homepage'),
    path('math-facts/', MathFactsView.as_view(), name='math-facts'),
    path('anagram-hunt/', AnagramHuntView.as_view(), name='anagram-hunt'),
]

play2learn/urls.py
from django.contrib import admin
from django.urls import path, include

from games.views import HomePageView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path('', HomePageView.as_view()),
    path('', include("games.urls"))
]

common/models.py
from django.db import models

# Create your models here.

games/models.py
from django.db import models

class GameScores(models.Model):

    """
    Add tracking history for both games that stores the time (the time 
    the user finished the game), game type (e.g., Math Facts Practice), 
    game settings (e.g., operation: multiplication, max number: 20), and 
    final score for each game.
    """

    MATH = "MATH FACTS"
    ANAGRAM = "ANAGRAM HUNT"
    GAME_CHOICES = [
    (MATH, "Math Facts"),
    (ANAGRAM, "Anagram Hunt")
    ]
    created = models.DateTimeField(auto_now_add=True)
    username = models.TextField()
    score = models.IntegerField()
    operation = models.TextField()
    gamelength = models.TextField()
    maxnum = models.TextField()
    game = models.TextField(choices=GAME_CHOICES, default=MATH)

    def __str__(self):
        return str(self.username)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

common/views.py
from django.shortcuts import render

# Create your views here.

games/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

class AboutUsView(TemplateView):
    template_name = 'pages/about_us.html'

class MathFactsView(TemplateView):
    template_name = "math-facts.html"

class AnagramHuntView(TemplateView):
    template_name = "anagram-hunt.html"

templates/_base_vue.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %}</title>
<!-- Bootstrap CSS CDN-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
<body>
  {% block main %}{% endblock %}
  <div id="app"></div>
  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/anagram-hunt.html
{% extends "_base_vue.html" %}

{% block title %}Anagram Hunt{% endblock %}
{% block main %}
  <h1>Anagram Hunt</h1>
  {{ block.super }}
{% endblock %} 

templates/math-facts.html
{% extends "_base_vue.html" %}

{% block title %}Math Facts{% endblock %}
{% block main %}
  <h1>Math Facts</h1>
  {{ block.super }}
{% endblock %}

templates/pages/_base.html
<!DOCTYPE html>
{% load static %}
{% block html %}
<html lang="en">
<head>
{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/main.css' %}" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/56e801b86d.js" crossorigin="anonymous"></script></script>
<script defer src="http://localhost:8080/js/chunk-vendors.js"></script>
<script defer src="http://localhost:8080/js/app.js"></script>
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}">
<title>{% block title %}{% endblock %} | DjangoPlay2Learn</title>
{% endblock head %}
</head>
<body>
{% block body %}
  <header>
    <nav class="navbar navbar-expand-lg">
      <a class="navbar-brand ms-3 me-5 text-light" href="{% url 'games:homepage' %}" style="font-family:fantasy; font-weight:bolder;">DjangoPlay2Learn</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-expanded="false"
        aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link text-light" href="{% url 'games:homepage' %}">Home
            </a>
          </li>
          <li class="nav-item ms-5 me-3">
            <a class="nav-link text-light" href="{% url 'games:games' %}">Games</a>
          </li>
          <li class="nav-item ms-5 me-3">
            <a class="nav-link text-light" href="{% url 'games:game-scores' %}">Leaderboards</a>
          </li>
          <li class="nav-item ms-5 me-3">
            <a class="nav-link text-light" href="{% url 'review' %}">Reviews</a>
          </li>
          {% if not user.is_authenticated %}
          <li class="nav-item ms-5">
            <a class="nav-link text-light" href="{% url 'account_login' %}">Log In</a>
          </li>
          <li class="nav-item ml-3 me-3">
            <a class="nav-link text-light" href="{% url 'account_signup' %}">Sign Up</a>
          </li>
          {% endif %}
          <!--{% if user.is_authenticated %}-->
          <!-- If user is not logged in, don't display li below -->
          <li class="nav-item dropdown ms-5">
            <a class="nav-link dropdown-toggle text-white"  href="#" id="navbarDropdown"
               role="button" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">
              My DjangoPlay2Learn
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'users:my_account' %}">My Account</a>
              <div class="dropdown-divider"></div>
              <!--<a class="dropdown-item" href="#">Log out</a>-->
              <form method="post" action="{% url 'account_logout' %}">
                {% csrf_token %}
                <button class="btn dropdown-item">Log out</button>
              </form>
            </div>
          </li>
          <!--{% endif %}-->
        </ul>
      </div>
    </nav>
  </header>

  <main class="pb-1">

    {% if messages %}
    <ul>
      {% for message in messages %}
        <div class="alert message{{ message.tags }} alert-dismissible text-center ms-3 text-white col-md-11 bg-success" role="alert">
          <strong><i class="fas fa-regular fa-thumbs-up me-2"></i>{{message}}</strong>
          <button type="button" class="close" data-dismiss="alert"
            aria-label="Close">
            <i class="fas fa-window-close"></i>
          </button>
        </div>
      {% endfor %}
    </ul>
    {% endif %}

    {% block main %}{% endblock %}
  </main>

  <footer>
    <nav class="navbar navbar-expand-lg">     
      <ul class="navbar-nav m-auto">
        <li class="nav-item ms-5 me-3">
          <a class="nav-link" href="{% url 'contact' %}" style="color: yellow;">Contact</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item ms-5 me-3">
          <a class="nav-link" href="{% url 'review-index' %}"  style="color: yellow;">Leave A Review</a>
        </li>
        <li class="nav-item ms-5 me-3">
          <a class="nav-link" href="{% url 'myreviews' %}"  style="color: yellow;">My Reviews</a>
        </li>
        <li class="nav-item ms-5 me-3">
          <a class="nav-link" href="{% url 'games:myscores' %}"  style="color: yellow;">Game Tracking</a>
        </li>
        {% endif %}
        {% if user.is_superuser %}
        <li class="nav-item ms-5 me-3">
          <a class="nav-link" href="/admin/" style="color: bisque;">Admin</a>
        </li>
        {% endif %}
      </ul>
    </nav>
  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js" integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
  {% endblock body %}
  </html>
  {% endblock html %}

templates/pages/about_us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block main %}
  <h2>About Us</h2>
  <p>We tell funny jokes.</p>
  <p><a href="{% url 'jobs:app' %}">Work for us.</a></p>
{% endblock %}

templates/pages/home.html
<!DOCTYPE html>

{% load static %}

{% block title %}Home{% endblock title %}
{% block main %}
  <h1 class="text-center text-warning">DjangoPlay2Learn</h1>
  <h4 class="text-center text-warning">Player Reviews:</h4>

  <!-- CAROUSEL -->
  <div class="carousel slide carousel-fade pb-2" id="homepage-carousel" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      {% for review in reviews %}
        {% if forloop.first %}
          <div class="carousel-item active">
        {% else %}
          <div class="carousel-item">
        {% endif %}
        <!--<blockquote>-->
        <div class="card border-2 border-primary border-rounded m-auto p-3 text-center" style="max-width: 50rem; background-image: linear-gradient(darkslateblue, indianred);">
          <h2 style="color: mintcream;">{{ review.game }}</h2>  <!-- MATH or ANAGRAM -->
          <hr />
          <h3 style="color: ivory;">{{ review.comment }}</h3>
          <h4 style="color: lightgoldenrodyellow">-- {{ review.username }}</h4>
          <h5 style="color: seashell" class="py-3">{{ review.created }}</h5>
        </div>
        <!--</blockquote>-->
      </div> <!-- for carousel-item above -->
      {%endfor%}
      </div> <!-- for carousel-item active above -->
    </div>
  </div>
  <!-- END CAROUSEL -->
{% endblock main %}